name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" --build-arg ENCRYPTION_PASSWORD="${{ secrets.ENCRYPTION_PASSWORD }}" .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem  # Write the SSH key to a file
          chmod 600 ec2_key.pem  # Set permissions for the key file

      - name: SSH to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            if [ $(docker ps -aq -f name=my-app) ]; then
                  docker stop my-app || true
                  docker rm my-app || true
            fi
            docker run -d -p 80:3000 \
              --name my-app \
              --network my-network \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} \
              -e HOST=${{ secrets.HOST }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          EOF
      - name: Test Deployment
        run: |
          echo "Waiting for the application to be ready..."
          sleep 10  # Wait for 10 seconds to allow the app to initialize

          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }}/health)
          echo "Received response code: $response"

          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status code: $response"
            exit 1
          else
            echo "Health check passed."
          fi
