name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: SSH to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:3000 \
              --name my-app \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          EOF

      - name: Test Deployment
        run: curl http://${{ secrets.EC2_PUBLIC_IP }}/health
